### ISSUE TITLE
List all Orders

### ISSUE THREAD

**Issue by myl525** [CSCI-GA-2820-FA24-003/orders#2]
**As a** customer
**I need** to be able to read all my orders
**So that** I can know what I've bought in the past
   
 ### Details and Assumptions
 * I can view all my orders by time order
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I've bought something
 When I try to view my orders
 Then all my past orders will show by time order
GET    /orders                  <- List all orders
```

**Comment by ChiChasesCheese** [comment]
The rest uri should be /orders/{customerID} ?
