### ISSUE TITLE
Add Health Check Endpoint

### ISSUE THREAD

**Issue by ztl2** [CSCI-GA-2820-FA24-003/orders#54]
**As a** programmer
**I need** a  check point
**So that** allowing Kubernetes to check service health  
   
 ### Details and Assumptions
 * Implement the /health endpoint in the service.
* Ensure it returns the expected response and status code.
   
 ### Acceptance Criteria  
   
 ```gherkin
Kubernetes can successfully use the /health endpoint to perform health checks.
The endpoint returns the correct response and status code when healthy.
```

**Comment by ChiChasesCheese** [comment]
I'll take this : )
