### ISSUE TITLE
Create the Database Model for Orders

### ISSUE THREAD

**Issue by ChiChasesCheese** [CSCI-GA-2820-FA24-003/orders#6]
**As a** developer on the orders team,
**I need** to create a database model for the orders resource,
**So that** we can store and retrieve order data in a structured and persistent manner, providing reliable data support for our microservice.

 ### Details and Assumptions

 * The order resource includes the following fields: Order ID, Customer ID, list of Order Items, Total Amount, Order Status, Creation Timestamp, and Update Timestamp.
 * PostgreSQL will be used as the database.
 * The database model will be defined using SQLAlchemy ORM to integrate seamlessly with the Flask application.

 ### Acceptance Criteria  
 ```gherkin
Given that order requires unique identifiers and other detailed information related to order
Then the database will be populated with all orders
 ```

**Comment by myl525** [comment]
Two tables: 
order(order_id, order_date, order_status, total_amount, address, customer_id)
order_item(order_id, product_id, quantity, price)
