### ISSUE TITLE
add a simple single page UI

### ISSUE THREAD

**Issue by ztl2** [CSCI-GA-2820-FA24-003/orders#74]
**As a** administer
**I need** an interface to manage orders
**So that** do something about orders 
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by mimferpo** [comment]
Here’s my understanding of the requirements as an example for single-page UI in "Given, When, Then" Format

- Given an admin is on the order management page,When they load the page, Then they should see a list of all #orders with details like Order ID, Customer Name, Date, Status, and Actions.


- Given the admin wants to find a specific order,When they use the search bar or filters,Then the list should update to show only matching orders.

- Given an admin wants to cancel an order,When they click "Cancel" for that order,Then the order is marked as "Canceled" and removed from active orders.

Hope it helps!
